### ISSUE TITLE
Change Version of Open API from 3.0 to 3.0.x

### ISSUE THREAD

**Issue by shidixit** [loopingz/webda.io#192]
it seems you have removed support for swagger command and added  openapi command support from version 1.0.0 . so we have to change commands from swagger to openapi . But after generating the document by openapi the document is not rendered in UI . when i looking the openapi template specification it tells that in document the "openapi" property should have semantic versioning(like 3.0.0) and not "3.0" . When i changed the version from 3.0 to 3.0.0 it worked . i see in [packages/core/src/core.ts](https://github.com/loopingz/webda.io/commit/3e35fc61b9ae5fb068c2bce117d9f31a04ab765e#diff-f63fb32fca85d8e177d6400ce078818a4815b80ac7a3319b60d3507354890992) file in exportOpenAPI method you have added openapi: "3.0".

**Comment by loopingz** [comment]
Fixed in fdd4d13e415f7c2a48f121bab56519d70f83f871
